Repository OpenCodeEra/OpenCodeEra, pull requests merged in 2023-10, with the labels that each got.

#51 Revamp the footer
  css/style.css
  css/style_footer.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#50 Our Team Page created and also fixed the footer issue of not sticking at bottom
  .github/ISSUE_TEMPLATE/feature_request.md
  css/style.css
  css/style_footer.css
  css/team_list_style.css
  data/Contributors.json
  data/Maintainers.json
  data/RulesForAddingData.md
  images/logo/github.png
  images/logo/linkedin.png
  javascript/team_list.js
  team_list.html
Labels: hacktoberfest, hacktoberfest-accepted

#54 Project-section added
  css/style.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#58 Updated the team page Navbar
  css/style_footer.css
  team_list.html
Labels: hacktoberfest, hacktoberfest-accepted

#68 Created FAQ section
  css/faq.css
  data/FAQ.json
  index.html
  javascript/faq.js
  team_list.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#69 Update style.css
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#80 fixed "projects" link
  index.html
  javascript/index.js
Labels: bug, hacktoberfest, hacktoberfest-accepted, hacktoberfest-accepted-2023, fixed

#81 Fixed gap between footer and faq
  index.html
Labels: UI/UX, hacktoberfest, hacktoberfest-accepted, hacktoberfest-accepted-2023

#84 added margin to input form
  css/style.css
Labels: enhancement, UI/UX, hacktoberfest, hacktoberfest-accepted, hacktoberfest-accepted-2023

#71 Added hover effects and styled the teams section
  css/style.css
  css/style_footer.css
  css/team_list_style.css
  index.html
  javascript/index.js
  team_list.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-accepted-2023

#91 Regarding issue #86
  css/style.css
  index.html
  javascript/index.js
  team_list.html
Labels: bug, hacktoberfest, hacktoberfest-accepted, hacktoberfest-accepted-2023

#105 fix: instagram and twitter logo
  index.html
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#109 some changes
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-accepted-2023, fixed

#108 Changed the CSS property for social icon hover effect
  css/team_list_style.css
Labels: good first issue, hacktoberfest, fixed

#103 fix the navbar issue and make it responsive
  css/style.css
  index.html
  javascript/menu.js
Labels: enhancement, Feature / Functionality, hacktoberfest, hacktoberfest-accepted, hacktoberfest-accepted-2023

#114 feat: Scroll Snap feature
  css/style.css
Labels: UI/UX, Feature / Functionality, hacktoberfest
